[package]
name = "pizza-time-server"
version = "0.0.1"
edition = "2021"

[dependencies]
axum = "0.7.5"
serde = "1.0.204"
sqlx = { version = "0.7.4", features = ["macros", "postgres", "runtime-tokio", "time", "uuid"] }
tokio = { version = "1.38.1", features = ["full"] }
